export const products = [
    {
      id: 1,
      title: "Whirlpool Air Conditioner",
      description: "| split AC | 1.0 Ton",
      price: "399",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTajUAR38LyTMKIYTclsHj7LfEmUPuKa1N6cA&usqp=CAU",
      quantity: 1,
    },
    {
      id: 2,
      title: "Whirlpool  Conditioner",
      description: "| Double Door | 1.5 Ton",
      price: "2500",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTajUAR38LyTMKIYTclsHj7LfEmUPuKa1N6cA&usqp=CAU",
      quantity: 1,
    },
    {
      id: 3,
      title: "Whirlpool  Conditioner",
      description: "| Double Door | 2.0 Ton",
      price: "3500",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTajUAR38LyTMKIYTclsHj7LfEmUPuKa1N6cA&usqp=CAU",
      quantity: 1,
    },
    {
      id: 4,
      title: "LG Refrigerator",
      description: "| Double Door | 120 Ltr",
      price: "500",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTajUAR38LyTMKIYTclsHj7LfEmUPuKa1N6cA&usqp=CAU",
      quantity: 1,
    },
    {
      id: 5,
      title: "LG Refrigerator",
      description: "| Double Door | 230 Ltr",
      price: "700",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTajUAR38LyTMKIYTclsHj7LfEmUPuKa1N6cA&usqp=CAU",
      quantity: 1,
    },
    {
      id: 6,
      title: "LG Refrigerator",
      description: "| Single Door| 260 Ltr",
      price: "850",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTajUAR38LyTMKIYTclsHj7LfEmUPuKa1N6cA&usqp=CAU",
      quantity: 1,
    },
    {
      id: 7,
      title: "Samsung Refrigerator",
      description: "| Single Door | 170 Ltr",
      price: "950",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTajUAR38LyTMKIYTclsHj7LfEmUPuKa1N6cA&usqp=CAU",
      quantity: 1,
    },
    {
      id: 8,
      title: "Samsung Refrigerator",
      description: "| LED | 55 inches",
      price: "750",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTajUAR38LyTMKIYTclsHj7LfEmUPuKa1N6cA&usqp=CAU",
      quantity: 1,
    },
    {
      id: 9,
      title: "LG TV",
      description: "| LED | 65 inches",
      price: "900",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTajUAR38LyTMKIYTclsHj7LfEmUPuKa1N6cA&usqp=CAU",
      quantity: 1,
    },
  ];